version: 2
updates:
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/html"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
  open-pull-requests-limit: 10
