language: python

dist: trusty
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env:
      - TOX_ENV=py37
    - python: 3.8
      dist: xenial
      env:
      - TOX_ENV=py38
    - python: 3.9
      dist: xenial
      env:
      - TOX_ENV=py39

install:
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
  - travis_retry pip install "tox" "coverage"
  - pip list --format=columns
  - cd html
  - npm --version
  - npm install
  - cd ..

  # Emacs Version Manager
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"
  - git clone https://github.com/cask/cask ~/.cask
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-24.4-travis --use --skip
  - emacs --version
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python test/PySrc/tests/validate_legacy_python.py && exit || exit 1 ; fi
  - travis_wait tox -e $TOX_ENV
  - emacs -Q --batch -L emacs-live-py-mode --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile emacs-live-py-mode/*.el
  - emacs -Q -nw -L emacs-live-py-mode -L plugin/PySrc -l live-py-mode.el -l live-py-test.el -f ert-run-tests-batch-and-exit
  - cd html
  - npm test -- --watchAll=false
  - cd ..

after_success:
  - pip install codecov
  - codecov -e TOX_ENV
